version: '3.1'

services:
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - tunnlr_db:/data/db

  client:
    build: client/
    restart: unless-stopped
    tty: true
    depends_on: 
      - db

  backend:
    build: backend/
    restart: unless-stopped
    depends_on: 
      - db

  frontend:
    build: frontend/
    restart: unless-stopped
    depends_on: 
      - backend
    ports:
      - 8082:80

volumes:
    tunnlr_db: